### ISSUE TITLE
Compiling sbpd against static libraries fails with multiple definitions of get_mac

### ISSUE THREAD

**Issue by ralph-irving** [coolio107/SqueezeButtonPi-Daemon#1]
/usr/lib/arm-linux-gnueabihf/libcrypto.a(gost89.o): In function `get_mac':
(.text+0x1d4c): multiple definition of `get_mac'
/tmp/ccrPqbY6.o:discovery.c:(.text+0xc4c): first defined here
collect2: error: ld returned 1 exit status
makefile:2: recipe for target 'sbpd' failed

Declaring the function static in discovery.c fixed the problem.
[duplicate-get_mac-patch.txt](https://github.com/coolio107/SqueezeButtonPi-Daemon/files/806939/duplicate-get_mac-patch.txt)

**Comment by coolio107** [comment]
Thanks for the heads-up.
Somehow I could not open you patch file.
If declaring "get_mac" static was the only change in there I have now applied it.

**Comment by ralph-irving** [comment]
Confirmed commit d4eef2dd74b23a3d5ba8191aa69c39400f0d79a7 now builds fine with static libs.
