### ISSUE TITLE
Play song button

### ISSUE THREAD

**Issue by frimdo** [coolio107/SqueezeButtonPi-Daemon#11]
Hi, I have a feature idea, which would allow to assign a button (or another signal, say I2C device, pipe, command, ...) to playing a particular album.

Example:
Button is pressed -> Album is added to playlist and first track of album is played

I am happy to try to implement this feature and (if successful) make a pull request to this repo. But first I wanted to ask, if you think it is possible to implement. If possible, do you have any tips or ideas that could help with implementation?

**Comment by paul-1** [comment]
That is already possible using the command config file.

**Comment by frimdo** [comment]
Is it? All commands I can see in readme are 
```
               PLAY:   Play/pause
               PREV:   Jump to previous track
               NEXT:   Jump to next track
               VOL+:   Increase volume
               VOL-:   Decrease volume
               POWR:   Toggle power state
```
How do you add an album to playlist?

**Comment by paul-1** [comment]
https://github.com/coolio107/SqueezeButtonPi-Daemon#command-configuration-file

Look at the LMS CLI documentation to see available commands.  https://forums.slimdevices.com/showthread.php?105297-Where-can-I-find-the-CLI-documentation

not sure which OS you using.   My fork is what pCP is using.  https://github.com/paul-1/SqueezeButtonPi-Daemon

**Comment by frimdo** [comment]
Oh my god, this is great! Thank you very much!
