### ISSUE TITLE
KY040 rotary encoder

### ISSUE THREAD

**Issue by marcelveldt** [coolio107/SqueezeButtonPi-Daemon#8]
Hi, thanks for this! Great on picoreplayer.

Just one question: Is it true that KY040 rotary encoders are not supported ?

**Comment by marcelveldt** [comment]
Nevermind, it works. The documentation is a bit wrong about the VOLM command as it should be VOLU.

All set, thanks for this!

**Comment by paul-1** [comment]
Documentation updated with #9
